### ISSUE TITLE
Datasets as a raster data source (tiff) should always be loaded as WMS

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#49]
Data sets that have a raster data source (usually tiff files) and have a WMS should always be loaded as WMS, regardless of the setting "PostgreSQL" vs "WMS".

Examples:
https://geo-i.so.ch/api/search/v2/?limit=10&filter=foreground&searchtext=Orthofoto

and more specifically:
https://geo-i.so.ch/api/dataproduct/v1/ch.so.agi.orthofoto_2017_rgb

Currently, I have the impression that in case PostgreSQL is the default and the modifier key is not active, that SoLocator tries to load the layer as PG and fails.

**Comment by 3nids** [comment]
This is a bit tricky here.
The parent item is the orthophoto with WMS.
But it contains sublayers point to WMS which actually doesn't exist on the server (ch.so.agi.orthofoto_2017_rgb_12_5cm and ch.so.agi.orthofoto_2017_rgb_5m).
So if you try to load as PG, the plugin:
1) creates the group in the layer tree
2) cannot load as PG since there is no PG source
3) read the WMS config
4) fails to load the layer since it doesn't exist on the server.

This sounds a bit too complicated to handle on the client side (i.e. rolling back and switch to WMS).

So, either fix this on the server side.
Or make this orthophoto be a background layer since it will always be loaded as WMS.

**Comment by andreasneumann** [comment]
Our suggestion is as follows (not ideal, but we don't see anything better):

If you hit a facade layer and one of the childs of the facade layer is a raster layer, SoLocator needs to stick to the data source of the parent facade layer, without creating a layer tree.

The drawback is that one can never load PG layers in a mixed raster/vector facade layer, but that is not so often the case.

While it isn't ideal that raster childs of a facade layer have an invalid WMS data source, just removing that one doesn't solve our case either, because our raster files are not exposed to the client.
