### ISSUE TITLE
Allow to select more than one sub layer of a group layer structure.

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#9]
![image](https://user-images.githubusercontent.com/884476/66566708-e8b65b00-eb65-11e9-88f8-74a5f48d3a4c.png)

**Comment by 3nids** [comment]
while this sounds like a good idea, there are some considerations on the workflow:

1) common parent vs distinct layers: if `Sondernutzungsplane` and `Natur / Landschaft` are selected, are they inserted with `Nutzunsplanung` as parent or as two distinct layers/groups?

2) If `Nutzunsplanung` and `Sondernutzungsplane` are selected, is  `Sondernutzungsplane` the only layer expected to be loaded or all the others too?

Question 2 would at least be solved by using checkboxes instead of a selection.

**Comment by andreasneumann** [comment]
Good questions.

Regarding 1: I think it would make sense to have Nutzungsplanung (Karte) as parent group. If the use doesn't like this, it can easily be reorganized afterwards. We can't make everybody happy without introducing a ton of options.

Regarding 2: if you can introduce checkboxes with a reasonable effort, this would be good - or we find a good logic together. I don't know what behaviour qt offers for such tree structures? Do we have any documentation for selection scenarios in a tree combobox in qt?

**Comment by 3nids** [comment]
2) I am on it now, basically you implement what you want (there is no default behavior, checking items has no influence on parent/children). I would propose that checking an item would affect all his children.
That would have an implication for one in the way that we only create what is checked, having a common parent being up to the user.

does this work for you?

**Comment by andreasneumann** [comment]
yeah - sounds fine to me.

**Comment by andreasneumann** [comment]
How about concentrating on the other things first - like loading PG layers with symbology - and then come back to this problem at the end of the project?

We also need to make sure we can load tables with only attributes (no geometry).

I'll need to dig up a test case (sample) for no-geometry tables.

**Comment by 3nids** [comment]
> like loading PG layers with symbology

this is already achieved since 0.5.5

> I'll need to dig up a test case (sample) for no-geometry tables.

yes please, it shouldn't be a big deal to enable this

**Comment by 3nids** [comment]
I'll branch out and keep this on the side for now
